# Generated by Django 5.1.4 on 2025-05-30 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('formed_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('pub_date', models.DateField(verbose_name='Date of publication.')),
                ('genre', models.CharField(choices=[('ROCK', 'Rock'), ('POP', 'Pop'), ('JAZZ', 'Jazz'), ('HIPHOP', 'Hip-Hop'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='albumz_app.artist')),
            ],
        ),
    ]
