# Generated by Django 5.1.4 on 2025-06-02 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='add_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of adding to the system.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='user_rating',
            field=models.IntegerField(default=0, verbose_name='Rating given by the owner of the album.'),
        ),
    ]
