# Generated by Django 5.1.4 on 2025-06-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumz_app', '0002_album_add_date_album_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='user_rating',
            field=models.IntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent'), (6, 'Best')], default=0, verbose_name='Rating given by the owner of the album.'),
        ),
    ]
