# Generated by Django 5.1.4 on 2025-06-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumz_app', '0003_alter_album_user_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albums', models.ManyToManyField(related_name='wishlists', to='albumz_app.album')),
            ],
        ),
    ]
