# Generated by Django 5.1.4 on 2025-06-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumz_app', '0004_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of publication.'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
