# Generated by Django 5.1.4 on 2025-06-04 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumz_app', '0005_alter_album_pub_date_alter_artist_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='albumz_app.wishlist')),
            ],
        ),
    ]
