# Generated by Django 5.1.4 on 2025-06-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumz_app', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='albums',
            field=models.ManyToManyField(related_name='users', to='albumz_app.album'),
        ),
    ]
