networks:
  app-tier:
    driver: bridge

services:
  postgresql:
    image: bitnami/postgresql:latest
    networks:
      - app-tier
    volumes:
      - persistence:/bitnami/postgresql
    env_file:
      - .env.prod
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    networks:
      - app-tier
    expose:
      - 8000
    volumes:
      - static_volume:/app/static/
    env_file:
      - prod.env
    depends_on:
      - postgresql
  nginx:
    image: nginx:alpine
    networks:
      - app-tier
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static/
    depends_on:
      - web

volumes:
  persistence:
  static_volume: